// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbnajlhxbyebbijvzirl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndibmFqbGh4YnllYmJpanZ6aXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTg4MDUsImV4cCI6MjA1ODU3NDgwNX0.mqt3dgeM85NxJC-M23ODHG4dLXy5ADeMgw_32iI11sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);